language: php

sudo: false
services:
  - memcached

php:
  - 7.1

before_script:
  - ecl install memcahced
  - composer install -n

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.1' ]; then php vendor/bin/coveralls; fi

after_success:
  - travis_retry php vendor/bin/coveralls -v
